auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title/

title:            yangk.tk
url:              http://yangsk.tk
feed:             /atom.xml
author:
    name:         杨少奎
    qq:      	  739042544
description:      "杨少奎的博客"
author_info:      <a href="http://yangsk.tk/about.html">杨少奎</a>

copyright:
    - Design by <a href="http://yangsk.tk/about.html" title="杨少奎" target="_blank">杨少奎</a> &copy; Copyright 2012